version: '3'

services:
  database:
    image: "postgres"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db:/var/lib/postgresql/data

  dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/build
    ports:
      - "80:8081"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASS=postgres
      - POSTGRES_NAME=database
      - ENVIRONMENT=LOCAL
    depends_on:
      - "database"
      - "cache"

  celery:
    build:
      context: .
      dockerfile: Dockerfile-celery
    command: celery worker --app=femr_onchain --loglevel=info --logfile=logs/celery.log
    volumes:
      - .:/build
    environment:
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on: 
      - "dev"
      - "redis"
      - "database"
  
  redis:
    image: redis:6-alpine

  cache:
   image: memcached
   entrypoint:
    - memcached
    - -m 64

volumes:
  db: