version: "3.9"
services:
  dev:
    build: .
    volumes:
      - .:/build
    ports:
      - "8081:8081"
    depends_on:
      - database
  database:
    image: "postgres"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data