version: '3'

services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - staticvol:/opt/app/static
      - mediavol:/opt/app/mediafiles
    depends_on:
      - "dev"

  database:
    image: "postgres"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db:/var/lib/postgresql/data

  dev:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: "./build-dev.sh"
    volumes:
      - .:/build
      - staticvol:/opt/app/static
      - mediavol:/opt/app/mediafiles
      - localdb:/opt/app/db
    environment:
      - DEBUG=True
      - QLDB_ENABLED="FALSE"
      - qldb_name="fEMR-OnChain-Test"
      - ADMIN_NAME=""
      - ADMIN_EMAIL=""
      - EMAIL_HOST=""
      - EMAIL_PORT=""
      - EMAIL_USERNAME=""
      - EMAIL_PASSWORD=""
      - DEFAULT_FROM_EMAIL=""
      - SERVER_EMAIL=""
      - ENVIRONMENT="LOCAL"
      - SECRET_KEY=2HY>fXi!dQ&(9Vf.XghCa;L6G=Ul4r-Bwqh>ae0RG3vIh1ZJ%T
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASS=postgres
      - POSTGRES_NAME=database
      - ENVIRONMENT=LOCAL
    depends_on:
      - "database"
      - "cache"

  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile-celery
    volumes:
      - .:/build
      - localdb:/opt/app/db
    entrypoint: "./build-celery-beat.sh"
    environment:
      - DEBUG=True
      - QLDB_ENABLED="FALSE"
      - qldb_name="fEMR-OnChain-Test"
      - ADMIN_NAME=""
      - ADMIN_EMAIL=""
      - EMAIL_HOST=""
      - EMAIL_PORT=""
      - EMAIL_USERNAME=""
      - EMAIL_PASSWORD=""
      - DEFAULT_FROM_EMAIL=""
      - SERVER_EMAIL=""
      - ENVIRONMENT="LOCAL"
      - SECRET_KEY=2HY>fXi!dQ&(9Vf.XghCa;L6G=Ul4r-Bwqh>ae0RG3vIh1ZJ%T
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASS=postgres
      - POSTGRES_NAME=database
      - ENVIRONMENT=LOCAL
    depends_on: 
      - "dev"
      - "redis"
      - "database"

  celery:
    build:
      context: .
      dockerfile: Dockerfile-celery
    volumes:
      - .:/build
      - localdb:/opt/app/db
    entrypoint: "./build-celery.sh"
    environment:
      - DEBUG=True
      - QLDB_ENABLED="FALSE"
      - qldb_name="fEMR-OnChain-Test"
      - ADMIN_NAME=""
      - ADMIN_EMAIL=""
      - EMAIL_HOST=""
      - EMAIL_PORT=""
      - EMAIL_USERNAME=""
      - EMAIL_PASSWORD=""
      - DEFAULT_FROM_EMAIL=""
      - SERVER_EMAIL=""
      - ENVIRONMENT="LOCAL"
      - SECRET_KEY=2HY>fXi!dQ&(9Vf.XghCa;L6G=Ul4r-Bwqh>ae0RG3vIh1ZJ%T
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASS=postgres
      - POSTGRES_NAME=database
      - ENVIRONMENT=LOCAL
    depends_on: 
      - "dev"
      - "redis"
      - "database"
  
  redis:
    image: redis:6-alpine

  cache:
   image: memcached
   entrypoint:
    - memcached
    - -m 64

volumes:
  db:
  staticvol:
  mediavol:
  localdb:
