# Generated by Django 3.2.3 on 2021-05-30 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_messages', '0002_message_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='read',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
