# pylint: skip-file
# Generated by Django 3.2.4 on 2021-06-11 15:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clinic_messages", "0004_auto_20210608_2159"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="timestamp",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
