# pylint: skip-file
# Generated by Django 3.1.7 on 2021-03-06 22:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_mr", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="supportticket",
            name="active",
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
