# pylint: skip-file
# Generated by Django 3.2.5 on 2021-08-03 18:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_mr", "0008_auto_20210306_1839"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="attachment",
            field=models.FileField(blank=True, null=True, upload_to="attachments/"),
        ),
        migrations.AddField(
            model_name="supportticket",
            name="attachment",
            field=models.FileField(blank=True, null=True, upload_to="attachments/"),
        ),
    ]
