# pylint: skip-file
# Generated by Django 3.2.6 on 2021-08-30 19:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_mr", "0009_auto_20210803_1440"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="supportticket",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
