# Generated by Django 3.2.9 on 2022-01-20 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organization",
            name="contract_start_date",
        ),
        migrations.AddField(
            model_name="instance",
            name="contract_start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
