# Generated by Django 3.2.10 on 2022-02-23 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_auto_20220120_1251"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryentry",
            name="count_unit",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name="inventoryentry",
            name="quantity_unit",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name="inventoryentry",
            name="strenth_unit",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
