# Generated by Django 3.0.8 on 2020-09-08 13:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0002_auto_20200906_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='shared_email_address',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='shared_phone_number',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='email_address',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
