# Generated by Django 3.2.8 on 2021-10-11 19:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0003_usersession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='encounter_close',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
