# Generated by Django 3.1.1 on 2020-09-15 13:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0004_auto_20200912_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
