# Generated by Django 3.2.8 on 2021-10-28 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_auto_20211012_2105"),
    ]

    operations = [
        migrations.AlterField(
            model_name="messageoftheday",
            name="text",
            field=models.CharField(max_length=2048),
        ),
    ]
