# Generated by Django 3.2.10 on 2022-03-05 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_alter_treatment_medication"),
    ]

    operations = [
        migrations.AddField(
            model_name="administrationschedule",
            name="modifier",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="treatment",
            name="amount",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
