# Generated by Django 3.1.1 on 2020-09-19 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200915_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
