# Generated by Django 3.2.8 on 2021-11-03 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_alter_messageoftheday_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patientencounter",
            name="current_medications",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="patientencounter",
            name="family_history",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="patientencounter",
            name="medical_history",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="patientencounter",
            name="pharmacy_notes",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="patientencounter",
            name="procedure",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="patientencounter",
            name="social_history",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
