# Generated by Django 3.1.1 on 2020-09-23 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_patient_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='ethnicity',
            field=models.CharField(choices=[('1', 'Hispanic or Latinx'), ('2', 'Not Hispanic or Latinx')], default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='race',
            field=models.CharField(choices=[('1', 'Native American or Native Alaskan'), ('2', 'Asian'), ('3', 'Black, African American'), ('4', 'Hispanic or Latinx'), ('5', 'White')], default=1, max_length=30),
            preserve_default=False,
        ),
    ]
