# Generated by Django 3.2.9 on 2021-11-05 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_auto_20211103_0955"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patientencounter",
            name="patient_history",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
