# Generated by Django 3.2.12 on 2022-03-05 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_alter_treatment_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="administrationschedule",
            name="modifier",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
