# Generated by Django 3.1.1 on 2020-10-01 14:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200923_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientencounter',
            name='oxygen_concentration',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
    ]
