# Generated by Django 3.1.1 on 2020-10-01 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20201001_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='femruser',
            name='change_password',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AlterField(
            model_name='femruser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
