# Generated by Django 3.2.9 on 2021-11-13 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_patientencounter_patient_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditentry',
            name='browser_user_agent',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='historyofpresentillness',
            name='narrative',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='historyofpresentillness',
            name='physical_examination',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
    ]
