# Generated by Django 3.2.8 on 2022-03-06 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_alter_administrationschedule_modifier"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryentry",
            name="amount",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
