# Generated by Django 3.2.9 on 2021-11-21 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_auto_20211111_1427"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historyofpresentillness",
            name="tests_ordered",
        ),
        migrations.AddField(
            model_name="historyofpresentillness",
            name="tests_ordered",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
