# Generated by Django 3.1.1 on 2020-10-09 13:40

from django.db import migrations, models
import django.db.models.deletion


def create_initial_campaign(apps, schema_editor):
    Instance = apps.get_model('main', 'Instance')
    Campaign = apps.get_model('main', 'Campaign')
    if not Campaign.objects.filter(name="Test").exists():
        Campaign.objects.create(name='Test', instance=Instance.objects.create(name="Test"))


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20201001_1407'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.instance')),
            ],
        ),
        migrations.RunPython(create_initial_campaign),
        migrations.AddField(
            model_name='femruser',
            name='campaign',
            field=models.ManyToManyField(to='main.Campaign'),
        ),
        migrations.AddField(
            model_name='patient',
            name='campaign',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.campaign'),
        ),
    ]
