# Generated by Django 3.1.1 on 2020-10-09 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20201009_0940'),
    ]

    operations = [
        migrations.RenameField(
            model_name='femruser',
            old_name='campaign',
            new_name='campaigns',
        ),
    ]
