# Generated by Django 3.2.12 on 2022-03-29 21:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_alter_patient_age"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventoryentry",
            name="amount",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="inventoryentry",
            name="count",
            field=models.BigIntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="inventoryentry",
            name="initial_quantity",
            field=models.BigIntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="inventoryentry",
            name="quantity",
            field=models.BigIntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="campaign_key",
            field=models.BigIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="treatment",
            name="amount",
            field=models.BigIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
