# Generated by Django 3.2.12 on 2022-04-13 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0012_auto_20220329_1702"),
    ]

    operations = [
        migrations.CreateModel(
            name="CSVExport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="export/")),
            ],
        ),
    ]
