# Generated by Django 3.1.1 on 2020-10-21 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20201009_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
