# Generated by Django 3.2.12 on 2022-04-16 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0014_csvexport_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="femruser",
            name="current_campaign",
            field=models.CharField(default="Test", max_length=100),
            preserve_default=False,
        ),
    ]
