# Generated by Django 3.2.12 on 2022-04-19 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0015_femruser_current_campaign"),
    ]

    operations = [
        migrations.AddField(
            model_name="csvexport",
            name="campaign",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.campaign",
            ),
        ),
        migrations.AddField(
            model_name="csvexport",
            name="timestamp",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
