# Generated by Django 3.1.1 on 2020-11-06 23:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_campaign_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='femruser',
            name='password_reset_last',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
