# Generated by Django 3.1.1 on 2020-11-11 15:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_femruser_password_reset_last'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='social_security_number',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='zip_code',
            field=models.CharField(blank=True, max_length=12, null=True, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='ZIP / Postal code'),
        ),
    ]
