# Generated by Django 3.2.13 on 2022-05-01 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0016_auto_20220419_1853"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditentry",
            name="system_user_agent",
            field=models.CharField(max_length=256, null=True),
        ),
    ]
