# Generated by Django 3.1.1 on 2020-11-16 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20201111_1041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientencounter',
            name='diabetes',
        ),
        migrations.AddField(
            model_name='patientencounter',
            name='community_health_worker_notes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='patientencounter',
            name='history_of_diabetes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientencounter',
            name='history_of_high_cholesterol',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientencounter',
            name='history_of_hypertension',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='patientencounter',
            name='alcohol',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='patientencounter',
            name='smoking',
            field=models.BooleanField(default=False),
        ),
    ]
