# Generated by Django 3.1.1 on 2020-11-16 18:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_patient_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientencounter',
            name='respiratory_rate',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(500), django.core.validators.MinValueValidator(1)]),
        ),
    ]
