# Generated by Django 3.1.1 on 2020-11-21 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_femruser_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='campaign',
        ),
        migrations.AddField(
            model_name='patient',
            name='campaign',
            field=models.ManyToManyField(to='main.Campaign'),
        ),
    ]
