# Generated by Django 3.1.1 on 2020-11-21 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20201121_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='units',
            field=models.CharField(choices=[('i', 'Imperial'), ('m', 'Metric')], default='m', max_length=30),
        ),
    ]
