# Generated by Django 3.1.1 on 2020-11-25 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_campaign_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='timezone',
            field=models.CharField(default='America/New_York', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='ethnicity',
            field=models.CharField(choices=[('1', 'Hispanic or Latinx'), ('2', 'Not Hispanic or Latinx'), ('3', 'Nondisclosed')], max_length=30),
        ),
        migrations.AlterField(
            model_name='patient',
            name='race',
            field=models.CharField(choices=[('1', 'Native American or Native Alaskan'), ('2', 'Asian'), ('3', 'Black, African American'), ('4', 'Hispanic or Latinx'), ('5', 'White'), ('6', 'Nondisclosed')], max_length=30),
        ),
    ]
