# Generated by Django 3.1.1 on 2020-12-02 18:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20201129_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientencounter',
            name='body_height_secondary',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
    ]
