# Generated by Django 3.1.1 on 2020-12-03 02:45

import django.core.validators
from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20201202_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientencounter',
            name='body_height_secondary',
            field=models.FloatField(validators=[main.models.ModifiedMaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
    ]
