# Generated by Django 3.1.1 on 2020-12-05 01:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_auto_20201202_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientencounter',
            name='heart_rate',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(170), django.core.validators.MinValueValidator(40)]),
        ),
        migrations.AlterField(
            model_name='patientencounter',
            name='oxygen_concentration',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(70)]),
        ),
    ]
