# Generated by Django 3.1.1 on 2020-12-07 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_auto_20201204_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditentry',
            name='campaign',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.campaign'),
            preserve_default=False,
        ),
    ]
