# Generated by Django 3.1.1 on 2020-12-08 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_auditentry_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='databasechangelog',
            name='campaign',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.campaign'),
            preserve_default=False,
        ),
    ]
