# Generated by Django 3.1.1 on 2020-12-08 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_databasechangelog_campaign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditentry',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.campaign'),
        ),
    ]
