# Generated by Django 3.1.1 on 2020-12-10 19:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_auto_20201208_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientencounter',
            name='body_weight',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(500), django.core.validators.MinValueValidator(0.25)]),
        ),
    ]
