# Generated by Django 3.1.1 on 2020-12-14 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_auto_20201210_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='sex_assigned_at_birth',
            field=models.CharField(choices=[('f', 'Female'), ('m', 'Male'), ('o', 'Other')], max_length=6),
        ),
    ]
