# Generated by Django 3.1.6 on 2021-02-09 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_auto_20201214_0830'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Allergy',
        ),
        migrations.DeleteModel(
            name='HealthConcern',
        ),
        migrations.DeleteModel(
            name='Immunization',
        ),
        migrations.RemoveField(
            model_name='labtest',
            name='test',
        ),
        migrations.DeleteModel(
            name='Medication',
        ),
        migrations.DeleteModel(
            name='Problem',
        ),
        migrations.DeleteModel(
            name='Procedure',
        ),
        migrations.DeleteModel(
            name='LabTest',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
