# Generated by Django 3.1.7 on 2021-03-07 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_auto_20210209_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientencounter',
            name='chief_complaint',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='patientencounter',
            name='diagnoses',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='patientencounter',
            name='patient_history',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='patientencounter',
            name='treatments',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
