# Generated by Django 3.1.7 on 2021-03-13 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_auto_20210306_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='telehealth',
            field=models.BooleanField(default=False),
        ),
    ]
