# Generated by Django 3.1.8 on 2021-04-23 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_auto_20210423_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='vitals',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
