# Generated by Django 3.1.7 on 2021-04-23 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_vitals_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrationSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=1024, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChiefComplaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=1024, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=1024, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=1024, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='patientencounter',
            name='chief_complaint',
        ),
        migrations.RemoveField(
            model_name='patientencounter',
            name='diagnoses',
        ),
        migrations.RemoveField(
            model_name='patientencounter',
            name='treatments',
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.IntegerField()),
                ('administration_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.administrationschedule')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.medication')),
            ],
        ),
        migrations.AddField(
            model_name='patientencounter',
            name='chief_complaint',
            field=models.ManyToManyField(to='main.ChiefComplaint'),
        ),
        migrations.AddField(
            model_name='patientencounter',
            name='diagnoses',
            field=models.ManyToManyField(to='main.Diagnosis'),
        ),
        migrations.AddField(
            model_name='patientencounter',
            name='treatments',
            field=models.ManyToManyField(to='main.Treatment'),
        ),
    ]
