# Generated by Django 3.1.7 on 2021-04-24 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_auto_20210424_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientencounter',
            name='chief_complaint',
            field=models.ManyToManyField(blank=True, to='main.ChiefComplaint'),
        ),
        migrations.AlterField(
            model_name='patientencounter',
            name='diagnoses',
            field=models.ManyToManyField(blank=True, to='main.Diagnosis'),
        ),
        migrations.AlterField(
            model_name='patientencounter',
            name='treatments',
            field=models.ManyToManyField(blank=True, to='main.Treatment'),
        ),
    ]
