# Generated by Django 3.2.1 on 2021-05-06 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_auto_20210429_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
