# Generated by Django 3.2.1 on 2021-05-11 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_treatment_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='campaign_key',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='race',
            field=models.CharField(choices=[('1', 'Native American or Native Alaskan'), ('2', 'Asian'), ('3', 'Black, African American'), ('4', 'Hispanic or Latinx'), ('5', 'Mixed Race'), ('6', 'White'), ('7', 'Nondisclosed')], max_length=30),
        ),
    ]
