# Generated by Django 3.2.1 on 2021-05-11 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0050_auto_20210511_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='campaign_key',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
