# Generated by Django 3.2.3 on 2021-05-13 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_alter_patient_campaign_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrationSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=1024, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='administration_schedule',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='medication',
        ),
        migrations.AddField(
            model_name='treatment',
            name='medication',
            field=models.ManyToManyField(blank=True, null=True, to='main.Medication'),
        ),
        migrations.AddField(
            model_name='treatment',
            name='administration_schedule',
            field=models.ManyToManyField(blank=True, null=True, to='main.AdministrationSchedule'),
        ),
    ]
