# Generated by Django 3.2.3 on 2021-05-30 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_auto_20210513_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='encounter_close',
            field=models.PositiveIntegerField(default=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientencounter',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='administration_schedule',
        ),
        migrations.AddField(
            model_name='treatment',
            name='administration_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.administrationschedule'),
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='medication',
        ),
        migrations.AddField(
            model_name='treatment',
            name='medication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.medication'),
        ),
    ]
