# Generated by Django 3.2.4 on 2021-06-03 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0053_auto_20210529_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientencounter',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
