# Generated by Django 3.2.4 on 2021-06-03 21:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0054_alter_patientencounter_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='main_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
