# Generated by Django 3.2.4 on 2021-06-04 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0055_alter_instance_main_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientDiagnosis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.diagnosis')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.patientencounter')),
            ],
        ),
        migrations.AlterField(
            model_name='treatment',
            name='diagnosis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.patientdiagnosis'),
        ),
    ]
