# Generated by Django 3.2.4 on 2021-06-05 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0056_auto_20210604_1416'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientdiagnosis',
            old_name='patient',
            new_name='encounter',
        ),
        migrations.AlterField(
            model_name='treatment',
            name='encounter',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.patientencounter'),
        ),
    ]
