# Generated by Django 3.2.4 on 2021-06-07 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0057_auto_20210604_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='prescriber',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
