# Generated by Django 3.2.4 on 2021-06-17 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0058_alter_treatment_prescriber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientdiagnosis',
            name='diagnosis',
        ),
        migrations.AddField(
            model_name='patientdiagnosis',
            name='diagnosis',
            field=models.ManyToManyField(to='main.Diagnosis'),
        ),
    ]
