# Generated by Django 3.2.4 on 2021-06-17 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0059_auto_20210617_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='chiefcomplaint',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
