# Generated by Django 3.2.4 on 2021-06-22 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0061_auto_20210617_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='diagnosis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.diagnosis'),
        ),
    ]
