# Generated by Django 3.2.4 on 2021-06-22 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0062_alter_treatment_diagnosis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='femruser',
            name='campaigns',
            field=models.ManyToManyField(blank=True, to='main.Campaign'),
        ),
    ]
