# Generated by Django 3.2.4 on 2021-06-24 17:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0063_alter_femruser_campaigns'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientencounter',
            name='current_medications',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='patientencounter',
            name='family_history',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='patientencounter',
            name='medical_history',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='patientencounter',
            name='social_history',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='administration_schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.administrationschedule', blank=True, null=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='treatment',
            name='days',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='treatment',
            name='medication',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.medication'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vitals',
            name='body_temperature',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(200), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='vitals',
            name='diastolic_blood_pressure',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(200), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='vitals',
            name='heart_rate',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(170), django.core.validators.MinValueValidator(40)]),
        ),
        migrations.AlterField(
            model_name='vitals',
            name='mean_arterial_pressure',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='vitals',
            name='systolic_blood_pressure',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(200), django.core.validators.MinValueValidator(1)]),
        ),
    ]
