# Generated by Django 3.2.4 on 2021-06-24 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0064_auto_20210624_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='administration_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.administrationschedule'),
        ),
    ]
