# Generated by Django 3.2.4 on 2021-06-29 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0064_auto_20210624_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientencounter',
            name='timestamp',
            field=models.DateTimeField(editable=False),
        ),
    ]
