# Generated by Django 3.2.5 on 2021-07-06 15:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0066_auto_20210629_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientencounter',
            name='weeks_pregnant',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(45), django.core.validators.MinValueValidator(0)]),
        ),
    ]
