# Generated by Django 3.2.5 on 2021-07-11 17:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0067_alter_patientencounter_weeks_pregnant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientencounter',
            name='body_height_primary',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(8), django.core.validators.MinValueValidator(0)]),
        ),
    ]
