# Generated by Django 3.2.5 on 2021-07-12 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0069_auto_20210711_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientencounter',
            name='campaign',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to='main.campaign'),
        ),
    ]
