# Generated by Django 3.2.5 on 2021-07-30 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0074_auto_20210730_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='country',
            field=models.CharField(default='Canada', max_length=30),
            preserve_default=False,
        ),
    ]
