# Generated by Django 3.2.5 on 2021-07-31 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0075_campaign_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientencounter',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
