# Generated by Django 3.2.5 on 2021-08-01 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0076_alter_patientencounter_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatment',
            name='medication',
        ),
        migrations.AddField(
            model_name='treatment',
            name='medication',
            field=models.ManyToManyField(blank=True, to='main.Medication'),
        ),
    ]
