# Generated by Django 3.2.5 on 2021-08-03 18:40

import django.core.validators
from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0077_auto_20210801_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientencounter',
            name='body_height_primary',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(8), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='patientencounter',
            name='body_height_secondary',
            field=models.FloatField(blank=True, null=True, validators=[main.models.ModifiedMaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='patientencounter',
            name='body_weight',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(500), django.core.validators.MinValueValidator(0.25)]),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='timestamp',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
