# Generated by Django 3.2.6 on 2021-08-25 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0080_auto_20210820_2022'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='inventoryentry',
            name='volume',
        ),
        migrations.AddField(
            model_name='inventoryentry',
            name='bottles',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventoryentry',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventoryentry',
            name='form',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.inventoryform'),
            preserve_default=False,
        ),
    ]
