# Generated by Django 3.2.6 on 2021-08-29 14:24

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0082_auto_20210827_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='inventory',
            field=models.ForeignKey(default=main.models.get_new_inventory, on_delete=django.db.models.deletion.CASCADE, to='main.inventory'),
        ),
    ]
