# Generated by Django 3.2.6 on 2021-08-30 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0083_alter_campaign_inventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSVUploadDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='csv')),
            ],
        ),
    ]
