# Generated by Django 3.2.6 on 2021-08-30 19:00

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0084_csvuploaddocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='organization',
            field=models.ForeignKey(default=main.models.get_test_org, on_delete=django.db.models.deletion.CASCADE, to='main.organization'),
        ),
    ]
