# Generated by Django 3.2.6 on 2021-08-31 19:18

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0086_auto_20210830_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ethnicity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='campaign',
            name='ethnicity_options',
            field=models.ManyToManyField(to='main.Ethnicity'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='race_options',
            field=models.ManyToManyField(to='main.Race'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='ethnicity',
            field=models.ForeignKey(default=main.models.get_nondisclosed_ethnicity, on_delete=django.db.models.deletion.CASCADE, to='main.ethnicity'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='race',
            field=models.ForeignKey(default=main.models.get_nondisclosed_race, on_delete=django.db.models.deletion.CASCADE, to='main.race'),
        ),
    ]
