# Generated by Django 3.2.6 on 2021-09-01 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0087_auto_20210831_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='ethnicity',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='race',
        ),
        migrations.AddField(
            model_name='patient',
            name='ethnicity_text',
            field=models.CharField(blank=True, choices=[('1', 'Hispanic or Latinx'), ('2', 'Not Hispanic or Latinx'), ('3', 'Nondisclosed')], db_column='ethnicity', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='race_text',
            field=models.CharField(blank=True, choices=[('1', 'Native American or Native Alaskan'), ('2', 'Asian'), ('3', 'Black, African American'), ('4', 'Hispanic or Latinx'), ('5', 'Mixed Race'), ('6', 'White'), ('7', 'Nondisclosed')], db_column='race', max_length=30, null=True),
        ),
    ]
