# Generated by Django 3.2.6 on 2021-09-01 02:19

from django.db import migrations, models
import django.db.models.deletion
import main.models


def process_text_race_ethnicity(apps, schema_editor):
    Patient = apps.get_model('main', 'Patient')
    for patient in Patient.objects.all():
        if patient.race_text is None and patient.race is not None:
            patient.race_text = patient.race
        if patient.ethnicity_text is None and patient.ethnicity is not None:
            patient.ethnicity_text = patient.ethnicity


def assign_new_race_ethnicity(apps, schema_editor):
    Patient = apps.get_model('main', 'Patient')
    Race = apps.get_model('main', 'Race')
    Ethnicity = apps.get_model('main', 'Ethnicity')
    for patient in Patient.objects.all():
        if patient.race is None and patient.race_text is not None:
            patient.race = Race.objects.get_or_create(name=patient.race_text)
        if patient.ethnicity is None and patient.ethnicity_text is not None:
            patient.ethnicity = Ethnicity.objects.get_or_create(name=patient.ethnicity_text)


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0087_auto_20210831_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='ethnicity_text',
            field=models.CharField(choices=[('1', 'Hispanic or Latinx'), ('2', 'Not Hispanic or Latinx'), ('3', 'Nondisclosed')], default='3', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='race_text',
            field=models.CharField(choices=[('1', 'Native American or Native Alaskan'), ('2', 'Asian'), ('3', 'Black, African American'), ('4', 'Hispanic or Latinx'), ('5', 'Mixed Race'), ('6', 'White'), ('7', 'Nondisclosed')], default='7', max_length=30),
            preserve_default=False,
        ),
        migrations.RunPython(process_text_race_ethnicity),
        migrations.AlterField(
            model_name='patient',
            name='ethnicity',
            field=models.ForeignKey(default=main.models.get_nondisclosed_ethnicity, on_delete=django.db.models.deletion.CASCADE, to='main.ethnicity'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='race',
            field=models.ForeignKey(default=main.models.get_nondisclosed_race, on_delete=django.db.models.deletion.CASCADE, to='main.race'),
        ),
        migrations.RunPython(assign_new_race_ethnicity)
    ]
