# Generated by Django 3.2.6 on 2021-09-01 05:00

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0088_auto_20210901_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='ethnicity',
            field=models.ForeignKey(blank=True, default=main.models.get_nondisclosed_ethnicity, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.ethnicity'),
        ),
        migrations.AddField(
            model_name='patient',
            name='race',
            field=models.ForeignKey(blank=True, default=main.models.get_nondisclosed_race, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.race'),
        ),
    ]
