# Generated by Django 3.2.6 on 2021-10-01 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0091_auto_20211001_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.state'),
        ),
    ]
