# Generated by Django 3.2.6 on 2021-10-01 14:27

from django.db import migrations


def state_data_migrate(apps, schema_editor):
    Patient = apps.get_model("main", "Patient")
    State = apps.get_model("main", "State")
    for p in Patient.objects.all():
        if p.state is None and p.state2 is not None:
            p.state = State.objects.get_or_create(name=p.state2)[0]
            p.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0092_patient_state'),
    ]

    operations = [
       migrations.RunPython(state_data_migrate),
    ]
