# Generated by Django 3.2.6 on 2021-10-01 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0093_patient_state_migrate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='ethnicity_text',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='race_text',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='state2',
        ),
    ]
