# Generated by Django 3.2.7 on 2021-10-06 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0095_alter_campaign_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvuploaddocument',
            name='mode_option',
            field=models.CharField(choices=[('1', 'New'), ('2', 'Update')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
