# Generated by Django 3.1.7 on 2021-03-06 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMR', '0005_auto_20210306_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportticket',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
